### ISSUE TITLE
sync meta groups in Moodle 2.8

### ISSUE THREAD

**Issue by EmilyULCC** [paulholden/moodle-local_metagroups#4]
Hi, I have installed 2014103100 on Moodle version 2.8.5 but it does not look like the sync is working. Can you confirm if this version works in 2.8 and if not when a new compatible version will be released?

Many thanks
Emily

**Comment by paulholden** [comment]
Hi @EmilyULCC how have you tested/confirmed this?

I've just installed the plugin in the latest master version (3.0) and it works fine, so will work on any supported version prior to that.
